# Generated by Django 6.0.3 on 2026-03-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepPs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='candidatura',
            constraint=models.UniqueConstraint(fields=('usuario', 'vaga'), name='unique_candidatura'),
        ),
    ]
