# Generated by Django 6.0.3 on 2026-03-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepPs', '0002_perfil_nickname_candidatura_unique_candidatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pergunta1', models.TextField(blank=True, null=True)),
                ('pergunta2', models.TextField(blank=True, null=True)),
                ('pergunta3', models.TextField(blank=True, null=True)),
                ('nicknames', models.CharField(blank=True, max_length=100, null=True)),
                ('plataformas', models.CharField(choices=[('ps', 'PokerStars'), ('partypoker', 'partypoker'), ('888poker', '888poker'), ('ggpoker', 'GGPoker'), ('outros', 'Outros')], max_length=100)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='candidatura',
            name='unique_candidatura',
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='vaga',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Candidatura',
        ),
        migrations.DeleteModel(
            name='Vaga',
        ),
    ]
