# Generated by Django 6.0.3 on 2026-03-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepPs', '0003_inscricao_remove_candidatura_unique_candidatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='plataformas',
            field=models.CharField(max_length=100),
        ),
    ]
