# Generated by Django 6.0.3 on 2026-03-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepPs', '0004_alter_inscricao_plataformas'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
